const { Paragraph, TextRun, HeadingLevel, AlignmentType, ExternalHyperlink, UnderlineType } = require("docx");
const REFS = require("./refs.js");
const { p, heading, caption } = require("./build.js");

// ---------- Results ----------
const results = [
  heading("3. Results", HeadingLevel.HEADING_1),

  heading("3.1 Point-based spatial analysis (RQ1)", HeadingLevel.HEADING_2),
  p("The point-based trajectory begins with mid-twentieth-century distance- and quadrat-based tests for departure from complete spatial randomness (CSR), formalized by Diggle (1976) and later systematized, along with their historical antecedents in forestry sampling and ecology, by Illian, Penttinen, Stoyan & Stoyan (2008). This first-order phase gave way to a second-order phase built around functional summary statistics — Ripley's K-function, the pair-correlation function, and the nearest-neighbour G- and empty-space F-functions — which could detect the scale and strength of clustering or regularity rather than merely reject CSR (Wiegand & Moloney, 2004; Perry, Miller & Enright, 2006). Ecological uptake of this toolkit was rapid but uneven: Loosmore & Ford (2006) showed that a widely used simulation-envelope procedure for the K- and g-statistics violated the assumptions of Monte Carlo inference and produced incorrect Type I error rates, illustrating that popularity and statistical correctness did not always advance together during this phase."),
  p("A consolidation phase followed, marked by comprehensive monographs (Wiegand & Moloney, 2013; Baddeley, Turner & Rubak, 2015) and, critically, by the arrival of the open-source R package spatstat, which Baddeley et al. (2026) describe as having “completely transformed” statistical practice for point processes by letting methodological research and software development proceed hand in hand. This software-enabled phase extended the point-process toolkit to inhomogeneous, marked, multitype, and higher-dimensional patterns, and to model families beyond the Poisson process (Cox, Gibbs, and cluster processes), as reviewed by Møller & Waagepetersen (2016). Two large-scale disciplinary reviews bookend this period from the applied side: Velázquez et al. (2016), surveying 308 ecology articles published 1992–2012, found that a standard canon of point pattern analysis had become established but that the majority of studies underused the methodological potential already available to them; Ben-Said (2021) updates this picture, again in plant ecology, and reports the same pattern of underuse alongside a persistent debate over minimum sample size."),
  p("Two further extensions define the current frontier. First, point processes have been extended beyond an unconstrained plane to more realistic supports: to linear networks, where Baddeley, Rakshit & Nair (2020) show that the choice of network distance metric is pivotal and that naively applying planar methods to network-constrained events (such as traffic accidents along roads) is a common and serious error; to spatially aggregated data lacking exact coordinates, for which Yamada et al. (2026) propose new statistics; and to three-dimensional point clouds from remote sensing and structural health monitoring (Momtaz Dargahi et al., 2020). Second, point processes have been extended in time, yielding a spatio-temporal point-process literature with its own review lineage (González, Rodríguez-Cortés, Cronie & Mateu, 2016; González et al., 2023). At the leading edge, Mateu & Jalilian (2022) couple point-process theory with deep neural networks, including variational-autoencoder generative models for building spatio-temporal point processes, signalling the point-based trajectory's entry into the GeoAI-augmented phase discussed in Section 3.4."),

  heading("3.2 Line-based spatial analysis: networks and trajectories (RQ2)", HeadingLevel.HEADING_2),
  p("The line-based trajectory is best understood as two historically distinct sub-lineages that only recently began to merge. The first, a GIScience network-analysis tradition, dates to some of the earliest GIS data structures: Curtin (2007) identifies network representations as “one of the earliest representations” in GIS, with a theoretical basis in graph theory and topology that enabled linear referencing and dynamic segmentation — the association of events and attributes with positions along a network rather than with planar coordinates (Curtin, 2009). Batty (2003) argued that GIScience's representational basis under-engaged with network dynamics relative to Euclidean space, a critique that anticipated the subsequent cross-pollination of geography with graph theory and physics-derived complex-network science. Ducruet & Beauguitte (2014) trace this cross-pollination in detail, noting that spatial science's engagement with non-planar, scale-free, and small-world network models (originating largely in sociology and physics) was comparatively recent and unevenly adopted among spatial scientists. Anderson & Dragićević (2020) extend this synthesis, arguing that most existing geospatial network research still characterizes static network structure rather than modeling how real spatial networks evolve, and advocate coupling geographic automata systems with network models to do so. Uitermark & Van Meeteren (2021) offer a complementary reframing, terming the result “geographical network analysis” and insisting that networks are situated, meaningful, and power-laden rather than abstract graphs — an explicitly geographic corrective to purely topological network science. By the mid-2020s, this tradition had matured to the point of being teachable as an accessible computational workflow (Cabrera, 2025)."),
  p("The second sub-lineage, trajectory data mining, emerged largely independently, out of mobile computing and data-mining venues rather than classical GIScience, once GPS- and mobile-phone-based location acquisition became widespread in the 2000s. Zheng's (2015) survey is the field-defining synthesis, organizing the literature into trajectory preprocessing, trajectory data management, and a family of mining tasks including pattern mining (Giannotti, Nanni, Pinelli & Pedreschi, 2007), clustering (Yuan et al., 2016), transportation-mode classification (Yang et al., 2018), and future-location or trajectory prediction (Georgiou, Tsoukatos & Sellis, 2018). Feng & Zhu (2016) situate this as a broad applied survey lineage in its own right, with preprocessing methods (cleaning, compression, segmentation, and map-matching) now systematic enough to support a dedicated methods review of 138 primary studies (Li et al., 2025), and with data-management concerns crystallizing into a distinct trajectory-data-warehouse modeling literature (Oueslati et al., 2023)."),
  p("The two sub-lineages show clear signs of reconvergence in the most recent literature. Baddeley, Rakshit & Nair's (2020) point-patterns-on-networks review is, in effect, classical point-process theory adapted to run on the trajectory-mining era's roads and rail networks. Chen et al. (2016) propose a network time-geographic data model explicitly motivated by “emerging spatiotemporal big data,” compressing three-dimensional time-geographic entities into a two-dimensional linear-referencing space so that classical spatial-database operations can be reused for trajectory-scale data volumes — a direct technical bridge between the network-theoretic and trajectory-mining sub-lineages."),

  heading("3.3 Polygon-based spatial analysis: areal data (RQ3)", HeadingLevel.HEADING_2),
  p("The polygon-based trajectory begins in the cartographic tradition of the choropleth map and in regional science's early recognition that aggregated areal data are rarely independent of their neighbours. Getis (2008) traces the formal concept of “spatial autocorrelation” to the late 1960s work of Dacey, Cliff and Ord, noting that the term itself was first used in 1967 and had earlier informal precursors in ideas such as distance decay; Getis (2007) reflects that the concept subsequently became, in his words, “the mainstay of the burgeoning field of spatial econometrics” following Luc Anselin's foundational synthesis. Moran's I became, and remains, the workhorse statistic of this phase, with a substantial later literature devoted to its mathematical reconstruction, generalization, and comparison with alternatives such as Geary's C (Chen, 2020; Ord & Getis, 2010, whose local Gi and Gi* statistics extended global autocorrelation to local indicators of spatial association, now widely known as LISA statistics)."),
  p("A parallel software trajectory closely mirrors the point-based tradition's spatstat/R arc, but on its own timeline: Anselin, Syabri & Kho (2005) document the transition from bespoke, loosely GIS-integrated spatial-statistics code toward the dedicated GeoDa application, and Anselin (2012) extends this narrative “from SpaceStat to CyberGIS,” explicitly framing decades of software evolution as driven jointly by methodological advances, the open-source movement, and Internet-enabled cyberinfrastructure — the same three forces, differently timed, that Baddeley et al. (2026) identify for point-process software. Bivand (2022) brings this comparison to the present, benchmarking modern R packages for areal data against PySAL and GeoDa on a shared census-tract case study. Multiscale extensions of geographically weighted regression (Kang et al., 2025) represent a further refinement of the local-modeling current opened by LISA statistics, allowing spatial process heterogeneity to vary by covariate as well as by location."),
  p("A methodologically distinct, more recent current within the polygon-based trajectory explicitly rejects the common practice of reducing a polygon to its centroid before applying point-based distance or association methods. Mu & Tong (2020) and Mu & Tribby (2021) show that centroid-based polygon-to-point distance measures can bias regression coefficient estimates, and propose new polygon-native distance metrics together with efficient computation algorithms; Godoy et al. (2022) develop an analogous polygon-native alternative to point-pattern association tests, adapting a toroidal-shift Monte Carlo procedure so that polygon geometry is preserved rather than discarded. This “polygon-first” current remains a minority strand relative to the dominant centroid-reduction practice, but it directly parallels the point-based trajectory's own extension to non-Euclidean, constrained supports (Section 3.1), suggesting a shared underlying methodological maturation across data models rather than an isolated areal-data phenomenon."),
  p("Finally, the polygon-based trajectory shows the same big-data and machine-learning pressures visible elsewhere in this review. Jawarneh et al. (2023) address approximate analytics over large georeferenced polygon data via simplification and stratified sampling; Heaton et al. (2017) report a multi-team predictive competition among methods for large spatial data; Ye et al. (2018), reviewing 209 articles on object-based image analysis, document a shift from per-pixel to per-polygon accuracy assessment; and Song & Wu (2020) propose a geographical detector model explicitly validated across point, line, and areal spatial data types within a single framework — a rare methodological bridge across all three data models discussed further in Section 4. Applied systematic reviews confirm the practical uptake of these trends: a review of 62 land-change-science studies (2015–2025) finds CA-Markov modeling and Random Forest classification, often combined with Google Earth Engine, as the currently dominant applied combination (Supiyandi et al., 2025), while a review of areal approaches in road safety documents a comparable, if slower, shift toward Bayesian and machine-learning models at the areal-unit level (Ziakopoulos & Yannis, 2020)."),

  heading("3.4 Cross-cutting trajectory: technological and methodological convergence (RQ4)", HeadingLevel.HEADING_2),
  p("Independent quantitative evidence from GIScience historiography corroborates the qualitative convergence described above. Bibliometric analyses of the field's overall research-topic evolution — 9,400 publications from 1991–2020 (Wu et al., 2022) and topic modeling over 16,096 abstracts from 1990–2017 (Huang, 2022) — both find that themes related to “moving object” analysis and volunteered geographic information have grown rapidly while classical themes such as digital elevation modeling have declined in relative share, a topic-level signature of exactly the point-to-trajectory and network-to-big-data shifts documented in Sections 3.1–3.2. Goodchild's (2010) twenty-year retrospective and Claramunt et al.'s (2023) review of the field since the NCGIA research agenda both frame GIScience as a field whose research priorities are driven substantially by external technological shocks rather than by internal theoretical necessity alone, consistent with the pattern observed across all three data-model trajectories in this review."),
  p("A second, distinct convergence is infrastructural: each trajectory independently replicated a transition from proprietary or bespoke software toward open-source ecosystems, at different but overlapping times — spatstat and R for point processes (Baddeley et al., 2026), GeoDa and PySAL for areal data (Anselin, 2012; Bivand, 2022), and a proliferating set of Python and R packages for network and trajectory analysis (Cabrera, 2025). This shared infrastructural convergence appears to be a necessary, though not sufficient, precondition for the third and most recent convergence: geospatial artificial intelligence (GeoAI)."),
  p("GeoAI is explicitly positioned in the literature as data-model-agnostic. Janowicz et al. (2019) and Li (2020) frame GeoAI as an emergent analytical layer over geospatial big data generally, not over any one geometry, and Mai et al. (2025) document its rapid growth across remote sensing, urban computing, Earth system science, cartography, and geospatial semantics. This agnosticism is visible concretely within each trajectory reviewed here: point processes coupled with neural networks (Mateu & Jalilian, 2022); machine learning applied to urban, largely polygon-referenced spatial analyses (Casali, Aydin & Comes, 2022, a scoping review); and deep-learning-based trajectory prediction (Georgiou et al., 2018) and spatially-explicit GeoAI in urban geography more broadly (a systematic review of 581 papers by an author team cited within the GeoAI literature). VoPham et al. (2018) and Saleh et al. (2025) extend this convergence to environmental epidemiology and human geography respectively, underscoring that the convergence is disciplinary as well as methodological. Importantly, Di Sabbata & Liu (2023) caution against over-stating the novelty of this moment, recalling a documented 1980s debate between Smith and Nystuen over the value of artificial intelligence for geography and characterizing the current GeoAI “spring” as the latest of several evolutionary, rather than revolutionary, waves — a caution echoed in this review's Discussion (Section 4)."),
  p("Big data and scale form a fourth, partially independent driver. Chen et al.'s (2016) network time-geographic data model, Jawarneh et al.'s (2023) polygon-simplification methods, and Heaton et al.'s (2017) large-spatial-data method competition each respond to a scale crisis that reached the point-, line-, and polygon-based trajectories at roughly the same historical moment (the 2010s) but for different proximate reasons — GPS ubiquity for trajectories, high-resolution remote sensing for polygons, and dense sensor networks for points — indicating convergent evolution under a common external pressure rather than direct methodological transfer."),
];

// ---------- Discussion ----------
const discussion = [
  heading("4. Discussion", HeadingLevel.HEADING_1),
  heading("4.1 A shared four-stage arc, on three different clocks", HeadingLevel.HEADING_2),
  p("Read together, the three trajectories share a recognizable four-stage arc: (1) a formal statistical or cartographic foundation; (2) consolidation around a small set of canonical summary statistics or algorithms; (3) an open-source software transition that decouples methodological research from proprietary tooling; and (4) a current AI- and big-data-augmented phase. What differs sharply is timing. Point-based foundations date to the 1970s (Diggle, 1976); polygon-based spatial-autocorrelation foundations date to the late 1960s (Getis, 2008); classical network data structures are contemporaneous with early GIS itself (Curtin, 2007). The trajectory-data-mining sub-lineage of the line-based trajectory, however, did not exist in any substantial form until GPS and mobile computing became widespread in the 2000s — a full analytical generation later than the other two data models' foundational phases. Rather than re-deriving statistical theory from first principles, this younger sub-lineage visibly imported mature point-process and network-analytic machinery once it needed it (Baddeley, Rakshit & Nair, 2020; Chen et al., 2016), illustrating methodological transfer across trajectories rather than purely independent, parallel invention."),
  heading("4.2 Convergence at the infrastructure layer, not the theory layer", HeadingLevel.HEADING_2),
  p("The convergence documented in Section 3.4 is real but should not be overstated. It occurs chiefly at the layer of computational infrastructure and AI tooling, not at the layer of underlying spatial theory. Point processes still fundamentally model event locations through intensity functions; areal data still cannot escape the Modifiable Areal Unit Problem and support-dependent aggregation bias, as directly evidenced by the centroid-distance bias documented by Mu & Tong (2020); and network- and trajectory-constrained data still require topologically appropriate, non-Euclidean distance metrics, a point Baddeley, Rakshit & Nair (2020) treat as pivotal rather than incidental. A practitioner who applies a generic machine-learning pipeline to any of the three geometries without respecting these irreducible, data-model-specific constraints risks exactly the kind of methodological error this review's included literature repeatedly warns against."),
  heading("4.3 A persistent translational lag", HeadingLevel.HEADING_2),
  p("A second cross-cutting pattern is a translational lag between methodological frontier and applied practice, visible independently within each trajectory. Within the point-based trajectory, two ecology-domain reviews a decade apart (Velázquez et al., 2016; Ben-Said, 2021) both report that practitioners underuse the statistical toolkit already available to them. Within the polygon-based trajectory, Ziakopoulos & Yannis (2020) document comparably slow uptake of Bayesian and machine-learning methods in applied road-safety research relative to the methodological literature's frontier. This recurring pattern suggests that the gap between what is methodologically possible and what is routinely practiced is a structural feature of spatial analysis as a field, not an artifact of any one data model or application domain."),
  heading("4.4 Gaps and priorities for future work (RQ5)", HeadingLevel.HEADING_2),
  p("Four gaps stand out. First, explicit cross-data-model methods remain rare: Song & Wu's (2020) geographical detector, validated across point, line, and areal data within a single framework, is a notable exception rather than the norm, and could serve as a template for further cross-model methodological development. Second, polygon-native, non-centroid-reduction methods (Mu & Tribby, 2021; Godoy et al., 2022) remain a minority practice despite demonstrated bias from the dominant centroid-reduction approach, and would benefit from wider tool support and default implementation in mainstream GIS software. Third, the interpretability and explainability of GeoAI models is flagged as an open problem across urban, network, and general geospatial applications alike (Mai et al., 2025; Saleh et al., 2025), cutting across all three data models rather than being specific to any one of them. Fourth, and reflexively, this review's own methods highlight a gap in the literature itself: genuinely systematic, multi-database reviews of spatial-analytical methodology are rare; most records in this review that used a formally systematic review methodology were themselves applied, domain-specific reviews (land change science, Supiyandi et al., 2025; road safety, Ziakopoulos & Yannis, 2020) rather than reviews of the underlying methods across application domains, which is the gap this review has attempted, within the limits described below, to begin filling."),
];

// ---------- Limitations ----------
const limitations = [
  heading("5. Limitations", HeadingLevel.HEADING_1),
  p("This review has five main limitations. First, and most importantly, it relies on a single information source (the Consensus/Semantic Scholar-backed corpus) without cross-validation against Scopus, Web of Science, PubMed, or IEEE Xplore; this likely undercounts venue-specific literature, including cartography-specific journals, conference proceedings not indexed by Semantic Scholar, and non-English scholarship. Second, screening was performed by a single reviewer (AI-assisted) without independent dual screening or a formal inter-rater reliability statistic, contrary to full PRISMA practice. Third, eligibility was assessed at the title/venue/abstract level only, without full-text retrieval or a formal quality or risk-of-bias appraisal instrument; this is defensible for a methodological and historiographic review, which is not assessing intervention effectiveness, but it remains a deviation from complete systematic-review rigor and means some included records may, on full-text reading, prove less relevant than their abstracts suggest. Fourth, two of nine planned queries (on kernel density estimation trends and on the history of spatial point process statistics specifically) failed due to search-API rate-limiting and were not retried, which may have narrowed point-based coverage slightly relative to the original search design; this is reported transparently in Table 1 rather than concealed. Fifth, this review's synthesis of the 68 included records is narrative rather than quantitative; where quantitative, bibliometric evidence was needed to corroborate qualitative patterns, we drew on other authors' published bibliometric analyses (Wu et al., 2022; Huang, 2022) rather than conducting new bibliometric analysis of our own record set. Finally, the search was conducted on a single date, 28 July 2026; the GeoAI and large-language-model-in-geospatial-science literature in particular is moving quickly enough that this review's account of the current frontier will date faster than its account of earlier, settled phases."),
];

// ---------- Conclusion ----------
const conclusion = [
  heading("6. Conclusion", HeadingLevel.HEADING_1),
  p("Point-based, line-based, and polygon-based spatial analysis arose from different disciplinary origins — ecological statistics, network and transportation geography, and cartographic/regional-science areal analysis, respectively — and matured through a broadly shared four-stage arc of statistical foundation, canonical-method consolidation, open-source software transition, and, most recently, AI- and big-data-augmented practice, though on markedly different historical timelines. The three trajectories are now converging at the level of computational infrastructure and artificial intelligence, but this convergence does not, and should not, erase the irreducible theoretical differences among the three underlying spatial data models: intensity-based event modeling for points, topologically constrained non-Euclidean distance for networks and trajectories, and aggregation- and support-dependent inference for polygons. For practitioners, the practical implication is that adopting a shared computational toolkit (open-source software, machine learning, GeoAI) is not a substitute for respecting these data-model-specific constraints. For methodologists, the priority gaps identified here — genuinely cross-data-model methods, wider adoption of polygon-native techniques, interpretable GeoAI across all three geometries, and closing the persistent lag between methodological frontier and applied practice — offer a concrete agenda. Finally, given this review's single-source, single-reviewer design, a future multi-database, dual-reviewer systematic review would be valuable to validate, extend, and quantitatively bibliometrically ground the trajectories described here."),
];

module.exports = { results, discussion, limitations, conclusion };
