#!/usr/bin/env python3
"""
Generate manuscript/references.bib directly from the screened corpus, so that
every citation in the manuscript resolves to a record that was actually
retrieved and coded.

Citation keys are <firstauthor><year>, disambiguated with a, b, c ... when
several records share a key.

NOTE: the federated index used for retrieval exposes title, authors, year,
journal and citation count, but not volume, issue, page range or DOI. Those
fields are therefore absent from the generated entries and must be completed
before submission (see README).
"""
import json
import os
import re
import unicodedata
from collections import defaultdict

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "manuscript")
os.makedirs(OUT, exist_ok=True)

TYPE_MAP = {
    "article": "article", "review": "article", "conference": "inproceedings",
    "preprint": "misc", "book": "book", "book_review": "article",
    "thesis": "phdthesis", "abstract": "misc", "correction": "article",
}


def ascii_fold(s):
    return "".join(c for c in unicodedata.normalize("NFKD", s)
                   if not unicodedata.combining(c))


def first_author_key(authors):
    first = authors.split(",")[0].strip()
    first = re.sub(r"\s+[A-Z]{1,3}$", "", first)          # drop initials
    first = re.sub(r"[^A-Za-z]", "", ascii_fold(first))
    return first.lower() or "anon"


def bib_escape(s):
    s = ascii_fold(str(s))
    for a, b in [("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_")]:
        s = s.replace(a, b)
    return s


def main():
    df = pd.read_csv(os.path.join(ROOT, "data", "corpus.csv"))
    df = df.drop_duplicates("url").sort_values(["year", "authors"])

    base = df.apply(lambda r: f"{first_author_key(r['authors'])}{int(r['year'])}",
                    axis=1)
    counts = defaultdict(int)
    keys = []
    dupes = base.duplicated(keep=False)
    for k, is_dupe in zip(base, dupes):
        if is_dupe:
            keys.append(f"{k}{chr(ord('a') + counts[k])}")
            counts[k] += 1
        else:
            keys.append(k)
    df = df.assign(key=keys)

    entries = []
    for _, r in df.iterrows():
        etype = TYPE_MAP.get(r["doc_type"], "article")
        authors = bib_escape(r["authors"]).replace(" et al", " and others")
        authors = " and ".join(a.strip() for a in authors.split(","))
        fields = [
            f"  author  = {{{authors}}}",
            f"  title   = {{{bib_escape(r['title'])}}}",
            f"  year    = {{{int(r['year'])}}}",
        ]
        jf = "journal" if etype == "article" else (
            "booktitle" if etype == "inproceedings" else "howpublished")
        if etype == "book":
            jf = "publisher"
        if etype == "phdthesis":
            jf = "school"
        fields.append(f"  {jf} = {{{bib_escape(r['journal'])}}}")
        fields.append(f"  note    = {{Record: \\url{{{r['url']}}}}}")
        entries.append("@%s{%s,\n%s\n}\n" % (etype, r["key"], ",\n".join(fields)))

    with open(os.path.join(OUT, "references.bib"), "w") as fh:
        fh.write("% Generated by scripts/make_bib.py from data/corpus.csv.\n"
                 "% Volume, issue, pages and DOI are not exposed by the\n"
                 "% retrieval index and must be completed before submission.\n\n")
        fh.write("\n".join(entries))

    lookup = dict(zip(df["title"], df["key"]))
    with open(os.path.join(ROOT, "data", "citekeys.json"), "w") as fh:
        json.dump(lookup, fh, indent=1)
    print(f"wrote {len(entries)} bib entries")


if __name__ == "__main__":
    main()
